'use strict';

/**
 * @namespace restak.query
 */
/**
 * @namespace restak.query.antlr
 */

/**
 * @interface Query
 * @memberof restak.query
 */

/**
 * Query a data store with a {@link QueryRequest|query request} object.
 *
 * @function
 * @name restak.query.Query#execute
 * @param {restak.query.QueryRequest} request - The query to execute against the set of data.
 * @param {restak.query.Query~QueryCallback} callback - The callback that handles the response.
 */

/**
 * Instructions for executing a query.
 *
 * @typedef QueryRequest
 * @memberof restak.query
 * @type {object}
 * @property {string} filter
 */

/**
 * The result of executing a query.
 * 
 * @typedef QueryResponse
 * @memberof restak.query
 * @property {string} filter
 * @property {Array} data
 */

/**
 * Callback definition for the execution of a query.
 *
 * @callback Query~QueryCallback
 * @memberof restak.query
 * @param {Object} error - An error if one occurred, otherwise null.
 * @param {restak.query.QueryResponse} response - The result of the query.
 * @see Query#execute
 */

// Generated classes by the antlr tool
/**
 * Generated by the antlr tool.
 *
 * @interface QueryListener
 * @memberof restak.query.antlr
 */